import { Request, Response, NextFunction } from 'express';
import { AppError } from './error.middleware';
import { JwtUtil } from '../utils/jwt.util';
import { auth as firebaseAuth, db } from '../config/firebase.config';

export interface AuthRequest extends Request {
    user?: {
        uid: string;
        email: string;
        tipoUsuario: string;
    };
}

/**
 * Authentication middleware that supports both:
 * 1. Custom JWT tokens (generated by our backend)
 * 2. Firebase ID tokens (from Firebase Auth SDK)
 */
export const authenticate = async (
    req: AuthRequest,
    res: Response,
    next: NextFunction
) => {
    try {
        const authHeader = req.headers.authorization;

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            throw new AppError(401, 'No token provided');
        }

        const token = authHeader.substring(7);

        // Try Firebase ID Token verification first
        try {
            const decodedFirebase = await firebaseAuth.verifyIdToken(token);

            // Get user info from Firestore to get tipoUsuario
            try {
                const userDoc = await db.collection('cuentas').doc(decodedFirebase.uid).get();
                if (userDoc.exists) {
                    const userData = userDoc.data();
                    req.user = {
                        uid: decodedFirebase.uid,
                        email: decodedFirebase.email || userData?.email || '',
                        tipoUsuario: userData?.tipoUsuario || 'POSTULANTE',
                    };
                } else {
                    // User exists in Firebase Auth but not in Firestore yet
                    req.user = {
                        uid: decodedFirebase.uid,
                        email: decodedFirebase.email || '',
                        tipoUsuario: 'POSTULANTE', // Default
                    };
                }
            } catch (firestoreError) {
                // Firestore error, use Firebase token data
                req.user = {
                    uid: decodedFirebase.uid,
                    email: decodedFirebase.email || '',
                    tipoUsuario: 'POSTULANTE',
                };
            }
            return next();
        } catch (firebaseError) {
            // Firebase verification failed, try custom JWT
            try {
                const decoded = JwtUtil.verifyToken(token);
                req.user = decoded;
                return next();
            } catch (jwtError: any) {
                // Both verifications failed
                if (jwtError.name === 'JsonWebTokenError') {
                    return next(new AppError(401, 'Invalid token'));
                }
                if (jwtError.name === 'TokenExpiredError') {
                    return next(new AppError(401, 'Token expired'));
                }
                throw jwtError;
            }
        }
    } catch (error: any) {
        next(error);
    }
};

export const authorize = (...allowedRoles: string[]) => {
    return (req: AuthRequest, res: Response, next: NextFunction) => {
        if (!req.user) {
            return next(new AppError(401, 'Not authenticated'));
        }

        if (!allowedRoles.includes(req.user.tipoUsuario)) {
            return next(new AppError(403, 'Not authorized to access this resource'));
        }

        next();
    };
};
